In [1]:
# load /home/s94zalek_hpc/3D-CODED/data/datas_surreal_test.pth

import torch

data_test = torch.load('/home/s94zalek_hpc/3D-CODED/data/datas_surreal_test.pth')
data_test.shape

torch.Size([200, 6890, 3])

In [3]:
import trimesh

template = trimesh.load('/home/s94zalek_hpc/shape_matching/data/SURREAL_full/template/template.ply')

In [2]:
import trimesh
import numpy as np

scene = trimesh.Scene()

# for i, idx in enumerate(range(0, 200, 20)):
#     mesh = trimesh.Trimesh(vertices=data_test[idx] + np.array([i, 0, 0]), faces=template.faces, process=False)
#     scene.add_geometry(mesh)
    
# scene.show()

In [7]:
import sys
import os
curr_dir = os.getcwd()
if 's94zalek_hpc' in curr_dir:
    user_name = 's94zalek_hpc'
else:
    user_name = 's94zalek'
sys.path.append(f'/home/{user_name}/shape_matching')

import my_code.datasets.surreal_dataset_3dc as surreal_dataset_3dc

In [18]:
import importlib
importlib.reload(surreal_dataset_3dc)

<module 'my_code.datasets.surreal_dataset_3dc' from '/home/s94zalek_hpc/shape_matching/my_code/datasets/surreal_dataset_3dc.py'>

In [23]:
dataset_test = surreal_dataset_3dc.TemplateSurrealDataset('/home/s94zalek_hpc/3D-CODED/data/datas_surreal_test.pth')
dataset_train = surreal_dataset_3dc.TemplateSurrealDataset('/home/s94zalek_hpc/3D-CODED/data/datas_surreal_train.pth')

In [ ]:
scene.geometry.clear()

# plot ['first'] and ['second'] meshes

mesh_first = trimesh.Trimesh(vertices=dataset[21]['first']['verts'], faces=dataset[21]['first']['faces'], process=False)
mesh_second = trimesh.Trimesh(vertices=dataset[21]['second']['verts'] + np.array([1, 0, 0]), faces=dataset[21]['second']['faces'], process=False)

scene.add_geometry(mesh_first)
scene.add_geometry(mesh_second)

scene.show()

In [30]:
len(dataset_train)

230000

In [ ]:
import trimesh
import numpy as np

scene.geometry.clear()

# random_idxs = np.random.choice(len(dataset_test), 20, replace=False)
random_idxs = np.arange(0, 230000, 10000)
for i, idx in enumerate(random_idxs):
    mesh = trimesh.Trimesh(vertices=dataset_train[idx]['second']['verts'] + np.array([i, 0, 0]),
                           faces=template.faces, process=False)
    scene.add_geometry(mesh)
    
scene.show()

In [2]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([-4, 5, -6])

t1 * torch.sign(t2)

tensor([-1,  2, -3])

In [1]:
# get n of files in /home/s94zalek_hpc/shape_matching/data/CAESAR/caesar-fitted-meshes
import os

len(os.listdir('/home/s94zalek_hpc/shape_matching/data/CAESAR/caesar-fitted-meshes'))

4309

In [2]:
# read file /home/s94zalek_hpc/shape_matching/data/CAESAR/caesar-fitted-meshes/CSR0001A.mat

file_caesar = '/home/s94zalek_hpc/shape_matching/data/CAESAR/caesar-fitted-meshes/CSR0001A.mat'

import scipy.io

data_caesar = scipy.io.loadmat(file_caesar)

data_caesar.keys()

dict_keys(['__header__', '__version__', '__globals__', 'points'])

In [5]:
data_caesar['points'].shape

(6449, 3)

In [6]:
# read /home/s94zalek_hpc/shape_matching/data/CAESAR/caesar/meanShape.mat

file_mean_shape = '/home/s94zalek_hpc/shape_matching/data/CAESAR/caesar/meanShape.mat'

data_mean_shape = scipy.io.loadmat(file_mean_shape)

for key in data_mean_shape.keys():
    print(key, data_mean_shape[key])
    

__header__ b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Tue Aug 12 11:40:25 2014'
__version__ 1.0
__globals__ []
points [[-1.33926000e-03  9.05487000e+01  7.99718000e+02]
 [-2.13881107e-01  7.99444097e+01  8.08583799e+02]
 [ 4.47694323e-01  9.94668743e+01  7.94246374e+02]
 ...
 [ 1.63805135e+02  2.37000950e+01  4.74036037e+01]
 [ 1.59371085e+02  4.62206403e+01  4.26767205e+01]
 [ 1.72352888e+02  7.94995389e+01  4.25441082e+01]]


In [ ]:
# read /home/s94zalek_hpc/shape_matching/data/CAESAR/caesar/model.dat
# as a mesh file

import trimesh

file_model = '/home/s94zalek_hpc/shape_matching/data/CAESAR/caesar/model.dat'

# mesh = trimesh.load(file_model)

with open(file_model, 'r') as f:
    lines = f.readlines()


n_vertices = int(lines[0].split()[0])
n_faces = int(lines[0].split()[1])
n_edges = int(lines[0].split()[2])

vertices = np.array([list(map(float, line.split()[:3])) for line in lines[1:1 + n_vertices]])
faces = np.array([list(map(int, line.split()[:3])) for line in lines[1 + n_vertices: 1 + n_vertices + n_faces]])
# faces = faces[:, 1:]

mesh_caesar = trimesh.Trimesh(vertices=vertices + np.array([1, 0, 0]), faces=faces, process=False)
# rotate by 90 degrees along x axis

mesh_caesar.vertices = np.dot(mesh_caesar.vertices, np.array([[1, 0, 0], [0, 0, -1], [0, 1, 0]]))


mesh_scape = trimesh.load('/home/s94zalek_hpc/shape_matching/data/SCAPE_r/off/mesh001.off')

mesh_scape.vertices *= 1000

# rotate by 90 degrees along y axis
mesh_scape.vertices = np.dot(mesh_scape.vertices, np.array([[0, 0, 1], [0, 1, 0], [-1, 0, 0]]))
# mesh_scape.vertices = np.dot(mesh_scape.vertices, np.array([[0, -1, 0], [1, 0, 0], [0, 0, 1]]))

# pcl_scape = trimesh.PointCloud(mesh_scape.vertices, colors=[1, 0, 0])

# print(mesh_scape)

scene.geometry.clear()



scene.add_geometry(mesh_caesar)
scene.add_geometry(mesh_scape)

# rescale the scene to the size of the mesh
# scene.camera.zoom_extents()



# scene.add_geometry(pcl_scape)

scene.show()



In [18]:
print(mesh_scape.vertices)

[[ 0.0454073   0.08321649 -0.33811596]
 [ 0.0460818   0.09463759 -0.33470798]
 [ 0.0319602   0.10948099 -0.31902797]
 ...
 [-0.0153254  -0.0822232   0.00731354]
 [-0.0346853  -0.0736474   0.00192538]
 [ 0.00540836 -0.63934095 -0.15509099]]


In [5]:
template_ifmatch = trimesh.load('/home/s94zalek_hpc/shape_matching/data/IFMatch/Template/template_hyppo.ply')
template_ifmatch

<trimesh.Trimesh(vertices.shape=(3889, 3), faces.shape=(7774, 3), name=`template_hyppo.ply`)>

In [ ]:
scene.geometry.clear()

scene.add_geometry(template_ifmatch)

scene.show()

In [ ]:
templates_3dc = '/home/s94zalek_hpc/shape_matching/data/SURREAL_full/template'

# for each ply file in templates_3dc, load it and add to the scene

scene.geometry.clear()

import os

for i,file in enumerate(os.listdir(templates_3dc)):
    if file.endswith('.ply') and 'hyppo' not in file:
        mesh = trimesh.load(os.path.join(templates_3dc, file))
        mesh.vertices += np.array([i, 0, 0])
        
        print(f'{i}: {file}')
        
        scene.add_geometry(mesh)
        
scene.show()